// src/Component/MenuData.js
const MenuData = [
  {
    id: 1,
    name: "Margherita Pizza",
    category: "Pizza",
    price: 250,
    description: "Classic cheese and tomato pizza with fresh basil.",
    image: "https://restaurantforsales.com/photobin/5978-1-l.jpg", // Add image path
  },
  {
    id: 2,
    name: "Pepperoni Pizza",
    category: "Pizza",
    price: 300,
    description: "Spicy pepperoni with mozzarella cheese and tomato sauce.",
    image: "https://th.bing.com/th/id/OIP.exKRDDaOIzQEMYIlEZ3hkwHaE9?w=900&h=602&rs=1&pid=ImgDetMain",
  },
  {
    id: 3,
    name: "Cheese Burger",
    category: "Burger",
    price: 180,
    description: "Grilled beef patty with melted cheese, lettuce, and tomato.",
    image: "https://cdn.openart.ai/stable_diffusion/ba3b9ab654237a8c8e68ca77e744b924ae39bafd_2000x2000.webp",
  },
  {
    id: 4,
    name: "Veg Burger",
    category: "Burger",
    price: 150,
    description: "Fresh vegetables and crispy Burger.",
    image: "https://thumbs.dreamstime.com/b/fresh-burger-close-up-black-background-69063036.jpg",
  },
  {
    id: 5,
    name: "Creamy White Sauce Pasta",
    category: "Pasta",
    price: 170,
    description: "Rich, creamy white sauce pasta with a velvety blend of cheese, butter, and herbs for the ultimate comfort food experience. .",
    image: "https://lilluna.com/wp-content/uploads/2017/10/penne-pasta-resize-3.jpg",
  },
  {
    id: 6,
    name: "Pasta Salad",
    category: "Pasta",
    price: 250,
    description: "A refreshing and flavorful pasta salad tossed with fresh veggies, herbs, and a zesty dressing for a perfect light meal.",
    image: "https://th.bing.com/th/id/OIP.LvtOEniN-LL3eZl3jDLWrQHaLH?w=1024&h=1536&rs=1&pid=ImgDetMain",
  },
  {
    id: 7,
    name: "Creamy Vegetable Sandiwch",
    category: "Sandwich",
    price: 200,
    description: "A deliciously creamy vegetable sandwich loaded with fresh veggies, flavorful spices, and a rich, cheesy spread for a perfect bite.",
    image: "https://shwetainthekitchen.com/wp-content/uploads/2020/08/IMG_9999-720x1080.jpg",
  },
  {
    id: 8,
    name: "Bomby Grilled Sandwich",
    category: "Sandwich",
    price: 190,
    description: "A spicy, cheesy Bombay grilled sandwich with chutneys, veggies, and crispy toast",
    image: "https://th.bing.com/th/id/OIP.UKCqejBxiPZq-ontQtIRdwAAAA?rs=1&pid=ImgDetMain",
  },
  {
    id: 9,
    name: "Grilled Cheese Sandwich",
    category: "Sandwich",
    price: 150,
    description: "A crispy, golden grilled cheese sandwich with gooey melted cheese in every bite.",
    image: "https://img.freepik.com/premium-photo/grilled-cheese-sandwich-hd-8k-wallpaper-stock-photographic-image_1030895-22829.jpg",
  },
  {
    id: 10,
    name: "French Fries",
     category: "Fries",
    price: 120,
    description: "Crispy, golden French fries, perfectly seasoned for a delicious crunch. ",
    image: "https://img.freepik.com/premium-photo/french-fries-hd-8k-vector-illustration-wallpaper-stock-image_915071-37816.jpg",
  },
  {
    id: 11,
    name: "Peri Peri French Fries",
     category: "Fries",
    price: 160,
    description: "Crispy French fries tossed in spicy peri peri seasoning for a bold, flavorful kick.",
    image: "https://as2.ftcdn.net/v2/jpg/02/64/93/61/1000_F_264936111_BQpzeGlPmdfE9SVSNd5K20MjSCn5mxnn.jpg",
  },
  {
    id: 12,
    name: "Chilli Cheese French Fries",
    category: "Fries",
    price: 180,
    description: "Crispy fries loaded with spicy chili and gooey melted cheese for the ultimate indulgence.",
    image: "https://studentmealsaver.files.wordpress.com/2023/04/fries.png",
  },
  {
    id: 13,
    name: "Noodles",
    category: "Noodles",
    price: 200,
    description: "Flavorful, stir-fried noodles tossed with fresh veggies and aromatic spices.",
    image: "https://png.pngtree.com/background/20230424/original/pngtree-bowl-of-noodles-with-chopsticks-being-poured-over-it-picture-image_2458455.jpg",
  },
  {
    id: 14,
    name: "Schezwan Noodles",
    category: "Noodles",
    price: 210,
    description: "Spicy and flavorful Schezwan noodles tossed with veggies and a fiery sauce.",
    image: "https://tgcrestaurant.in/wp-content/uploads/2023/10/Untitled-14.jpg",
  },
  {
    id: 15,
    name: "Noodles Manchurian",
    category: "Noodles",
    price: 220,
    description: "A delicious combo of spicy noodles and crispy Manchurian balls tossed in flavorful sauces..",
    image: "https://img.freepik.com/premium-photo/manchurian-hakka-schezwan-noodles_1124848-11959.jpg",
  },
  {
    id: 16,
    name: "Manchurian",
    category: "Manchurian",
    price: 180,
    description: "Crispy, flavorful Manchurian balls tossed in a spicy, tangy sauce",
    image: "https://recipes.timesofindia.com/thumb/53241077.cms?width=1200&height=1200",
  },
  {
    id: 17,
    name: "Manchurian Rice",
    category: "Rice",
    price: 230,
    description: "Fragrant rice tossed with spicy Manchurian gravy and fresh veggies for a flavorful delight..",
    image: "https://i.ytimg.com/vi/KSmI5jkBQFw/maxresdefault.jpg",
  },
  {
    id: 18,
    name: "Schezwan Rice",
    category: "Rice",
    price: 180,
    description: "Spicy and flavorful Schezwan rice tossed with veggies and bold seasonings.",
    image: "https://th.bing.com/th/id/OIP.jg_mO03e_mY2517GA0tsDwAAAA?w=300&h=300&rs=1&pid=ImgDetMain",
  },
  {
    id: 19,
    name: "Pulao",
    category: "Rice",
    price: 100,
    description: "Aromatic and flavorful pulao cooked with fragrant spices and fresh vegetables. .",
    image: "https://th.bing.com/th/id/OIP.0TSR3c3b02LtpvApX27_4wHaJQ?rs=1&pid=ImgDetMain",
  },
  {
    id: 20,
    name: "Paneer Pulao",
    category: "Rice",
    price: 160,
    description: "Fragrant paneer pulao cooked with aromatic spices, basmati rice, and soft paneer cubes.",
    image: "https://thatdeliciousdish.com/wp-content/uploads/2019/01/Paneer-Butter-Pulao-1-1.jpg",
  },
  {
    id: 21,
    name: "Paneer Rolls",
    category: "Rolls",
    price: 90,
    description: "Soft and flavorful paneer rolls stuffed with spiced paneer and fresh veggies, wrapped in a warm roti.",
    image: "https://spicecravings.com/wp-content/uploads/2020/12/Paneer-kathi-Roll-Featured-1.jpg",
  },
  {
    id: 22,
    name: "Noodles Rolls",
    category: "Rolls",
    price: 79,
    description: "A spicy and flavorful noodles roll wrapped in a soft roti with fresh veggies and sauces.",
    image: "https://thatdeliciousdish.com/wp-content/uploads/2019/05/Veg-Noodles-Wrap-4-1010x1024.jpg",
  },
  {
    id: 23,
    name: "Dry Manchurian",
    category: "Manchurian",
    price: 150,
    description: "Crispy, golden Manchurian balls tossed in flavorful spices and sauces for a perfect dry snack.",
    image: " https://www.cookingwithsiddhi.com/wp-content/uploads/2020/11/veg-manchurian-dry.jpeg",
  },
  {
    id: 24,
    name: "Veg Burger",
    category: "Burger",
    price: 199,
    description: "A crispy veggie patty with fresh lettuce, juicy tomatoes  melting cheese, and tangy mayo, all in a soft toasted bun",
    image: " https://www.amomstake.com/wp-content/uploads/2014/03/Veggie-Burger.jpg",
  },
  {
    id: 25,
    name: "Combo Burger Meal",
    category: "Burger",
    price: 270,
    description: " A delicious burger served with crispy fries and a refreshing drink, making it the perfect meal deal!",
    image: "  https://fox8.com/wp-content/uploads/sites/12/2023/07/jalapeno.png?w=900",
  },
  {
    id: 26,
    name: "Fried & Burger Combo",
    category: "Burger",
    price: 250,
    description: "Enjoy a juicy burger paired with crispy golden fries for the ultimate satisfying meal! .",
    image: "  https://th.bing.com/th/id/OIP.GR4vnaudwwtYR2uUsbmUNwHaEe?w=626&h=378&rs=1&pid=ImgDetMain",
  },
  {
    id: 27,
    name: "Double Pizza Combo",
    category: "Pizza",
    price: 399,
    description: "Enjoy two delicious pizzas of your choice, paired with a side of garlic bread and a refreshing drink! Perfect for sharing! .",
    image: "https://product-assets.faasos.io/production/product/image_1631300467133_Two_Classic_Veg_Medium_Pizza_Combo.jpg",
  },

  {
    id: 28,
    name: "Ultimate Pizza Combo",
    category: "Pizza",
    price: 599,
    description: "Get a delicious pizza of your choice, a refreshing drink, and a rich, gooey Choco Lava cake for the perfect meal .",
    image: "https://product-assets.faasos.io/production/product/image_1602156511766_Overload_Veg_Pizza_Combo.jpg",
  },

];


export default MenuData;
